using UnityEngine;
public class BGMController : MonoBehaviour
{
    public AudioClip undetectedBGM;
    public AudioClip discoveryBGM;
    //public EnemySaikoro enemySaikoro;
    private AudioSource audioSource; // ‰¹ºÄ¶—p‚ÌAudioSource
    private bool undet = false;
    private bool dis = false;
    void Start()
    {
        audioSource = GetComponent<AudioSource>();
        if (audioSource == null)
        {
            audioSource = gameObject.AddComponent<AudioSource>(); // AudioSource‚ª‚È‚¯‚ê‚Î’Ç‰Á
        }
        audioSource.loop = true;

        audioSource.clip = undetectedBGM;
        audioSource.Play(); // –¢”­Œ©‚ÌBGM‚ğÄ¶
    }
    void Update()
    {
        /*if (!enemySaikoro.discovery && !undet)
        {
            audioSource.Stop(); // Œ»İ‚ÌBGM‚ğ’â~
            audioSource.clip = undetectedBGM;
            audioSource.Play(); // –¢”­Œ©‚ÌBGM‚ğÄ¶
            undet = true;
            dis = false;
        }
        else if (enemySaikoro.discovery && !dis)
        {
            audioSource.Stop(); // Œ»İ‚ÌBGM‚ğ’â~
            audioSource.clip = discoveryBGM;
            audioSource.Play(); // ”­Œ©‚ÌBGM‚ğÄ¶
            undet = false;
            dis = true;
        }*/
    }
}
